apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: certs
  namespace: docker-registry
  labels:
      app: docker-registry
spec:      
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi
