apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gitlab
  namespace: gitlab
  labels:
    app: gitlab
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: gitlab
    spec:
      serviceAccountName: default
      containers:
      - name: gitlab
        image: gitlab/gitlab-ce
        env:
        ## General GitLab Configs
        - name: external_url
          value: 'http://172.20.142.62:10080'
        ports:
        - name: ssh
          containerPort: 22
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        livenessProbe:
          httpGet:
             path: /help
             port: http
          # This pod takes a very long time to start up. Be cautious when
          # lowering this value to avoid Pod death during startup.
          initialDelaySeconds: 200
          timeoutSeconds: 15
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 10
          #readinessProbe:
          #httpGet:
          #  path: /help
          #  port: http
          #initialDelaySeconds: 60
          #timeoutSeconds: 1
          #periodSeconds: 10
          #successThreshold: 1
          #failureThreshold: 3
        volumeMounts:
        - name: gitlab-etc
          mountPath: /etc/gitlab
        - name: gitlab-data
          mountPath: /var/opt/gitlab
        - name: gitlab-logs
          mountPath: /var/log/gitlab
          #  - name: gitlab-reconfigure
          # mountPath: /var/log/gitlab/reconfigure
        resources:
      volumes:
      - name: gitlab-etc
        persistentVolumeClaim:
            claimName: gitlab-etc
      - name: gitlab-data
        persistentVolumeClaim:
            claimName: gitlab-data
      - name: gitlab-logs
        persistentVolumeClaim:
            claimName: gitlab-logs
            # - name: gitlab-reconfigure
            #persistentVolumeClaim:
            #claimName: gitlab-reconfigure
