apiVersion: v1
kind: Service
metadata:
  name: gitlab-test
  namespace: gitlab
spec:
  ports:
  - port: 10080
    name: web
    protocol: TCP
    targetPort: 80
  - port: 10022
    name: ssh
    protocol: TCP
    targetPort: 22
  - port: 10443
    name: secure
    protocol: TCP
    targetPort: 443
  selector:
    app: gitlab-test
  sessionAffinity: None
  type: LoadBalancer
