apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-test-data
  namespace: gitlab-test
  labels:
    type: nfs
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: nfs-lsbt.iba
    path: "/storage/share/gitlab-test/data"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-test-etc
  namespace: gitlab-test
  labels:
    type: nfs
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: nfs-lsbt.iba
    path: "/storage/share/gitlab-test/etc"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-test-logs
  namespace: gitlab-test
  labels:
    type: nfs
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: nfs-lsbt.iba
    path: "/storage/share/gitlab-test/logs"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-test-reconfigure
  namespace: gitlab-test
  labels:
    type: nfs
spec:
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: nfs-lsbt.iba
    path: "/storage/share/gitlab/logs/reconfigure"
