apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-test-data
  namespace: gitlab-test
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-test-etc
  namespace: gitlab-test
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-test-logs
  namespace: gitlab-test
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-test-reconfigure
  namespace: gitlab-test
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
