apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-apls-home
  namespace: jenkins
  labels:
    type: nfs
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: nfs-lsbt.iba
    path: "/storage/share/jenkins/appulse"
