apiVersion: v1
kind: PersistentVolume
metadata:
  name: apache2-www
  namespace: web-servers
  labels:
    type: nfs
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: nfs-lsbt.iba
    path: "/storage//share/apache2/www/html"
