apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: apache2-www
  namespace: web-servers
  labels:
    app: apache2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
