apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: docker-registry
  namespace: docker-registry
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: docker-registry
    spec:
      containers:
      - name: docker-registry
        image: registry:2
        env:
        - name: REGISTRY_HTTP_TLS_CERTIFICATE
          value: /docker/certs/domain.crt
        - name: REGISTRY_HTTP_TLS_KEY
          value: /docker/certs/domain.key
        - name: REGISTRY_HTTP_ADDR
          value: 0.0.0.0:5000
        - name: REGISTRY_STORAGE_DELETE_ENABLED
          value: "true"
        - name: REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY
          value: /docker/storage
        # HTPASSWD
        - name: REGISTRY_AUTH
          value: htpasswd
        - name: REGISTRY_AUTH_HTPASSWD_REALM
          value: "Registry Realm"
        - name: REGISTRY_AUTH_HTPASSWD_PATH
          value: /docker/auth/htpasswd
        ports:
          - name: registry-port
            containerPort: 5000
          - containerPort: 443
        volumeMounts:
        - mountPath: /docker/storage
          name: storage
        - mountPath: /docker/certs
          name: certs
        - mountPath: /docker/auth
          name: auth
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: storage
      - name: certs
        persistentVolumeClaim:
          claimName: certs
      - name: auth
        persistentVolumeClaim:
          claimName: auth
      restartPolicy: Always
