apiVersion: v1
kind: PersistentVolume
metadata:
  name: docker-registry-storage
  labels:
    type: nfs
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: nfs-lsbt.iba
    path: /storage/share/docker-registry/storage
