apiVersion: v1
kind: PersistentVolume
metadata:
  name: nexus-data
  namespace: nexus
  labels:
    type: nfs
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: nfs-lsbt.iba
    path: "/storage/share/nexus-data"
