apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-dev-conf        
  namespace: mysql
  labels:
    app: tconstructor
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
