apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexus-data 
  namespace: nexus
  labels:
      app: nexus-sonatype
spec:      
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
