apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nagios-test
  namespace: nagios
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nagios-test
    spec:
      containers:
      - name: nagios-test
        image: docker-lsbt.iba:5000/k8s-nagios
        ports:
          - name: http
            containerPort: 80
            protocol: TCP

        volumeMounts:
        - mountPath: /var/log/nagios
          name: nagios-pvc
          subPath: test/log

        - mountPath: /etc/nagios
          name: nagios-pvc
          subPath: test/cfg

        - mountPath: /usr/lib64/nagios/plugins
          name: nagios-pvc
          subPath: test/plugins

      volumes:
      - name: nagios-pvc
        persistentVolumeClaim:
          claimName: nagios-pvc

      restartPolicy: Always
