apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nagios-pvc
  namespace: nagios
  labels:
    app: nagios-prod
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Mi
