apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: adminer
  namespace: adminer
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: adminer
    spec:
      containers:
      - image: adminer
        name: adminer
        ports:
        - containerPort: 8080
