apiVersion: v1
kind: PersistentVolume
metadata:
  name: nagios-pv
  namespace: nagios
  labels:
    type: nfs
spec:
  capacity:
    storage: 20Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: ms-storage.iba
    path: /storage/pv/nagios
