apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-dev-conf
  namespace: mysql
  labels:
    type: nfs
spec:
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: nfs-lsbt.iba
    path: "/storage/share/mysql/dev/conf"
