apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-dev-data
  namespace: mysql
  labels:
    type: nfs
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: nfs-lsbt.iba
    path: "/storage/share/mysql/dev/data"
