apiVersion: v1
kind: Service
metadata:
  name: mysql-dev
  namespace: mysql
spec:
  ports:
  - port: 3306
    name: mysql-port
    protocol: TCP
    targetPort: 3306
  externalIPs:
    - 172.20.142.62
