apiVersion: v1
kind: PersistentVolume
metadata:
  name: apache2-logs
  namespace: web-servers
  labels:
    type: nfs
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: nfs-lsbt.iba
    path: "/storage//share/apache2/logs"
