apiVersion: v1
kind: Service
metadata:
  name: jenkins-tc
  namespace: jenkins
spec:
  ports:
  - port: 8090
    name: master
    protocol: TCP
    targetPort: 8080
  - port: 50000
    name: agent
    protocol: TCP
    targetPort: 50000
  selector:
    app: jenkins-tc
  sessionAffinity: None
  type: LoadBalancer
