apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-data
  namespace: gitlab
  labels:
    type: nfs
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: nfs-lsbt.iba
    path: "/storage/share/gitlab/data"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-etc
  namespace: gitlab
  labels:
    type: nfs
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: nfs-lsbt.iba
    path: "/storage/share/gitlab/etc"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-logs
  namespace: gitlab
  labels:
    type: nfs
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: nfs-lsbt.iba
    path: "/storage/share/gitlab/logs"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-reconfigure
  namespace: gitlab
  labels:
    type: nfs
spec:
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: nfs-lsbt.iba
    path: "/storage/share/gitlab/logs/reconfigure"
