apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jenkins-test
  namespace: jenkins
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: jenkins-test
    spec:
      containers:
      - name: jenkins-test
        image: jenkins:latest
        ports:
          - name: jenkins-master
            containerPort: 8082
          - name: jenkins-slave
            containerPort: 50002
        volumeMounts:
        - mountPath: /var/jenkins_home
          name: jenkins-home
        resources:
          limits:
            cpu: 500m
            memory: 1500Mi
          requests:
            cpu: 500m
            memory: 1500Mi
      volumes:
      - name: jenkins-home
        persistentVolumeClaim:
          claimName: jenkins-test-home
      restartPolicy: Always
