apiVersion: v1
kind: Service
metadata:
  name: jenkins-test
  namespace: jenkins
spec:
  ports:
  - port: 8082
    name: master
    protocol: TCP
    targetPort: 8082
  - port: 50002
    name: agent
    protocol: TCP
    targetPort: 50002
  selector:
    app: jenkins-test
  sessionAffinity: None
  externalIPs:
  - 172.20.142.59
