apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: adminer
  namespace: adminer
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: adminer
    spec:
      containers:
      - image: adminer
        name: adminer
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: adminer
  namespace: adminer
spec:
  ports:
  - port: 8080
    name: adminer-port
    protocol: TCP
    targetPort: 8080
  externalIPs:
    - 172.20.142.61  
